[build]
  publish = "dist"
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  NODE_OPTIONS = "--max-old-space-size=4096"
  VITE_LEGACY_BUILD = "false"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[functions]
  node_bundler = "esbuild"
